### ISSUE TITLE
Adopting Module

### ISSUE THREAD

**Issue by tenajsystems** [warrenpnz/puppet-aide#8]
@warrenpnz since you are no longer maintaining this, do you mind if I adopt the module?

**Comment by warrenpnz** [comment]
Certainly. If you fork it, I will set up a new README with a redirect

**Comment by alexjfisher** [comment]
Alternatively, you could consider migrating the module to [Vox Pupuli](https://voxpupuli.org/) and have it maintained there?  Let me know what you think.

**Comment by alexjfisher** [comment]
@tenajsystems Would that work for you?

**Comment by tenajsystems** [comment]
@alexjfisher Thanks for the offer but I think I will maintain it myself

**Comment by alexjfisher** [comment]
That's a shame.  I'm sure we'd have been happy to sort out merge access for you at VP.

**Comment by tenajsystems** [comment]
@warrenpnz I will let you know once I fork it.

**Comment by tenajsystems** [comment]
> Certainly. If you fork it, I will set up a new README with a redirect

@warrenpnz as mentioned earlier, I have forked the repo and converted the module to PDK. The link to the repo is: ```https://github.com/indiana-university/puppet-aide``` and the link to the puppet forge is: ```https://forge.puppet.com/iu/aide``` Once again, thank you for letting me adopt the module. I will take very good care of it.
